name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Jalankan setiap kali ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject API Key
        run: |
          # Mengganti string process.env.API_KEY dengan key asli dari Secrets
          sed -i "s|process.env.API_KEY|'${{ secrets.GEMINI_API_KEY }}'|g" services/geminiService.ts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Mengunggah seluruh root folder
